-- ─────────────────────────────────────────────────────────────────────────────
-- NOM-024-SSA3-2012 §6.5 — Identificación de pacientes
-- Adds CURP and required identity fields to profiles.
-- CURP is the unique patient identifier mandated by RENAPO.
-- ─────────────────────────────────────────────────────────────────────────────

-- CURP: 18-char alphanumeric, format validated by check constraint.
-- Pattern: 4 letters | 6 digit date | H/M | 2-char state | 3 consonants | 2 homoclave
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS curp              text,
  ADD COLUMN IF NOT EXISTS primer_apellido   text,
  ADD COLUMN IF NOT EXISTS segundo_apellido  text,
  ADD COLUMN IF NOT EXISTS estado_nacimiento char(2),   -- INEGI code (01-32, NE, 00)
  ADD COLUMN IF NOT EXISTS nacionalidad      char(3) DEFAULT 'MEX';  -- RENAPO code

-- CURP format constraint (NOM-024 §6.5.1: must not be autogenerated)
ALTER TABLE profiles
  ADD CONSTRAINT curp_format CHECK (
    curp IS NULL OR curp ~ '^[A-Z]{4}[0-9]{6}[HM][A-Z]{2}[A-Z]{3}[A-Z0-9]{2}$'
  );

-- CURP must be unique across all users (NOM-024 §6.5.1: identifier único)
-- NULLs do not violate UNIQUE in PostgreSQL.
ALTER TABLE profiles
  ADD CONSTRAINT curp_unique UNIQUE (curp);

-- estado_nacimiento must match INEGI 2-char codes or special values
ALTER TABLE profiles
  ADD CONSTRAINT estado_nacimiento_format CHECK (
    estado_nacimiento IS NULL
    OR estado_nacimiento ~ '^(0[1-9]|[12][0-9]|3[02]|NE|00)$'
  );

-- nacionalidad: 3 uppercase chars per RENAPO catalog
ALTER TABLE profiles
  ADD CONSTRAINT nacionalidad_format CHECK (
    nacionalidad IS NULL OR nacionalidad ~ '^[A-Z]{3}$'
  );

-- Indexes for identity lookups
CREATE INDEX IF NOT EXISTS profiles_curp_idx ON profiles (curp) WHERE curp IS NOT NULL;

-- ── Comments ─────────────────────────────────────────────────────────────────
COMMENT ON COLUMN profiles.curp              IS 'NOM-024 §6.5: CURP validado por RENAPO. 18 chars. No autogenerar.';
COMMENT ON COLUMN profiles.primer_apellido   IS 'NOM-024 §6.5: Primer apellido del documento probatorio. Sin abreviaturas.';
COMMENT ON COLUMN profiles.segundo_apellido  IS 'NOM-024 §6.5: Segundo apellido (opcional).';
COMMENT ON COLUMN profiles.estado_nacimiento IS 'NOM-024 §6.5: Clave INEGI entidad federativa nacimiento (EDONAC). NE=extranjero, 00=no disponible.';
COMMENT ON COLUMN profiles.nacionalidad      IS 'NOM-024 §6.5: Clave RENAPO nacionalidad. Default MEX. NND=no disponible.';
